### ISSUE TITLE
Same chip on RK71

### ISSUE THREAD

**Issue by gauravmanmode** [carlossless/sh68f90a-experiments#1]
Hi, I have same chip BYK916 on my Rk71 keyboard, want to port QMK.
Can i contribute with anything

**Comment by carlossless** [comment]
Hey @gauravmanmode,

Since this project uses sdcc and targets a 8051 target, it's very unlikely that this will ever become a true QMK port. That said, I aim to implement core functionality like keyboard layouts as close as possible to QMK to make porting them easier.

If you want this firmware to work on your RK71 then an obvious way to help would be to go ahead and port it, although I would only recommend doing that if you:
* Have a full dump of the stock firmware, so that you can restore it if something goes wrong
  * https://github.com/gashtaan/sinowealth-8051-dumper
  * https://github.com/carlossless/sinowealth-kb-tool
* Have a tool to write firmware without the use of the ISP bootloader, since it's very easy to brick it
  * Any sinowealth programming tool, like the sinolink. It's what I own and use and you can find them easily on taobao or aliexpress
* Can analyze how your keyboard is wired up (continuity checks, building a partial schematic)

Also, I would ask to hold off trying to port anything until I fully implement usb functionality (most likely in around 2 weeks from now).

**Comment by gauravmanmode** [comment]
okay i will wait until you implement usb.
also, do i need sinolink, is it really that brickable?

**Comment by carlossless** [comment]
@gauravmanmode yes, it's extremely easy to lose the ability to launch into ISP. I wouldn't recommend working on this experimental firmware without a way to restore the original firmware.

**Comment by carlossless** [comment]
@gauravmanmode I have pushed in working USB functionality, FYI

**Comment by gauravmanmode** [comment]
Amazing, you did it in such a few days. 
Thanks, I'm gonna try and make a port for RK71.

**Comment by arefinx** [comment]
> Amazing, you did it in such a few days. Thanks, I'm gonna try and make a port for RK71.

Hi, are you able to port it for your rk71? I have a rk61 with the same chip

**Comment by gauravmanmode** [comment]
There is already a branch for  rk61 [here](https://github.com/carlossless/smk/tree/nicarran-rk61-v2)
