### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by Nono9k** [carlossless/sh68f90a-experiments#11]
Hey! So I recently got this E-yooso Z11 for $3 (yes really), smk seems quite interesting so I thought why not test it, i do not have reflashing tools so if I mess up it's kinda game over for the kb, but i can just buy another $3 one. I'm willing to install it i just need some help figuring out how lol, Thanks!

**Comment by carlossless** [comment]
I'll try to add documentation with more details on how to build the firmware in the future, but for now, it's provided as is.  As a starting place, you can check [flake.nix](https://github.com/carlossless/smk/blob/master/flake.nix) for the different tools that are required for smk development, or even better, consider using [nix](https://nixos.org/) with the same flake file.

Btw, I actually decided to purchase an e-yooso z11 keyboard because I didn't have any other keyboards to test against other than my nuphy-air60. Stay tuned for more updates.

**Comment by Nono9k** [comment]
Thanks for the response, I'm actually ordering a second one lol, I'll try to do the firmware now and tell you how to goes

**Comment by Nono9k** [comment]
On seconds thoughts I might just wait until documentation lol, this is breaking my brain

**Comment by carlossless** [comment]
I'm capturing some of my progress with this keyboard here: https://github.com/carlossless/smk/issues/12

**Comment by carlossless** [comment]
I added some documentation. It's not a lot, but with the build setup more streamlined it should be easier to get started with building, modifying, and porting.
