### ISSUE TITLE
Genesis Thor 300

### ISSUE THREAD

**Issue by Th3KillinJok3** [carlossless/sh68f90a-experiments#6]
Hey Carlossless, great work on the smk so far!
I was scouring the internet to find:
- Genesis Thor 300 firmware as mine is jumbled upon dumping
- Additional Firmware that could be used.

With support for the retro chip is scarce, finding info is a tad confusing.

Question is whether works on SMK are still ongoing?
How can I help to add Genesis Thor 300 and Hykker X Range to support for SMK?
I currently own 3 Genesis Thor 300 I bought for parts, so testing field is there ;)

**Comment by carlossless** [comment]
Hey,

I'm still actively working on smk, but my free time is split between it and other projects I have going on, so progress is somewhat slow.

Right now I'm reorganizing this project in order to make it possible to simultaneously support and build for different MCUs (including the sh68f881), keyboards, and layouts. I would advise you to wait until that's merged into the main branch.

If you're keen to get smk working on your device as soon as possible, you could fork this project and start adapting it to your device already, though, I would recommend getting a dedicated programmer like the sinolink first, as it's very easy to brick the mechanism these devices use to launch into the ISP bootloader. Also, keep in mind that at this point, smk still lacks features and has a variety of known and unknown bugs that need to be fixed before I would recommend using it on your main keyboard. 

If you don't want to go ahead with a fork, documenting how your devices are connected is the next best thing. (e.g. schematics).

Right now I don't own a sh68f881-based device, so testing support would be definitely helpful in the future!

**Comment by carlossless** [comment]
Just an update: the project is in a much better shape to accept more keyboards and layouts. I may be able to acquire a Genesis Thor 300 keyboard and try porting SMK to it (and the sh68f811 platform).

**Comment by carlossless** [comment]
I got the keyboard, tracking progress here: https://github.com/carlossless/smk/issues/16
